---
version: 0.2
phases:
  install:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 533267123805.dkr.ecr.us-east-1.amazonaws.com
    
       
  build:
    commands:
      - docker build -t demoecsrepo .
      - docker tag demoecsrepo:latest 533267123805.dkr.ecr.us-east-1.amazonaws.com/demoecsrepo:latest

  post_build:
    commands:
      - docker push 533267123805.dkr.ecr.us-east-1.amazonaws.com/demoecsrepo:latest
      
artifacts:
  files: build.json